### ISSUE TITLE
Travis build not working

### ISSUE THREAD

**Issue by micahcochran** [LASzip/LASzip#20]
I noticed that Travis wasn't working due to the cmake version being too low.

I found two ways to fix this: (1) switch VM image to Trusty or (2) use a backport of cmake.

(1) Switch to Trusty
```yaml
sudo: required
dist: trusty
```

(2) cmake backport
```yaml
# install backport of cmake v 2.8.11  (Travis on 2016-03-08 has cmake 2.8.7, which isn't compatible with the cmake file.)
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
```

Both bulids don't seem to build laszippertest giving this error:
`./scripts/ci/script.sh: line 12: ./bin/laszippertest: No such file or directory`

[Trusty build](https://travis-ci.org/micahcochran/LASzip/builds/114546120)
[backport build](https://travis-ci.org/micahcochran/LASzip/builds/114558268) -- this also has `tree .` output to show what files were built

This probably isn't a big deal, since this project doesn't seem to have that many developers.  This may be a won't fix or something to fix later. I just notice this problem, and I'm not planning to contribute C++ code.
